Better link failure modal copy
mbta/skate pull request #1031
Opened 2021-02-12 18:16 UTC by lemald

Ticket: [More detailed modals when linking to a run from a notification isn't possible](https://app.asana.com/0/1148853526253426/1199873489874876/f)

Note that I'm still trying to reproduce / dig into an issue with runs saying they're on break when the break is actually done, but so far I've tried several cases with no luck.

The current API for fetching schedules relies on GTFS trip IDs, and the notifications code already maps the original run to trip IDs. Fetching a run by run ID would require also knowing the current service, which is a bit of a hairier problem. I think the run ID -> GTFS trip ID(s) -> run ID mapping should be consistent, though. For fetching runs for potentially several trip IDs I just did multiple API calls because the number is going to be at most a few in any given case and going forward we'll probably want to use run IDs / block IDs where possible, but let me know if you'd rather that I make the back-end support querying for several GTFS trip IDs at once.

This does result in `incativeNotificationModal.tsx` having a fair bit of code that deals with the structure of run data. I'm not sure that there's really another good place to put it, though, since the logic is so specific to this use case. Let me know if you have any thoughts, though.

2021-02-17 19:29 UTC, lemald commented
@phildarnowsky should be ready for your review for real now after discussion with Akira.

2021-02-19 13:54 UTC, phildarnowsky commented on assets/tests/hooks/useMinischedule.test.ts
> +      .mockImplementationOnce(() => instantPromise(run2))
TIL

2021-02-19 19:59 UTC, phildarnowsky requested changes
Small changes noted.

2021-02-19 20:02 UTC, lemald commented on assets/src/components/inactiveNotificationModal.tsx
> +): [RunScheduleRelationship, RunId | null] => {
Yup, exactly, it's a tuple.

2021-02-19 21:34 UTC, phildarnowsky approved these changes

2021-02-19 21:37 UTC, merged