Chore: Clean up old FS custom events / identification code
mbta/skate pull request #1624
Opened 2022-07-06 19:51 UTC by lxhughes

Asana: https://app.asana.com/0/home/50959463118296/1202286302110707

2022-07-07 14:48 UTC, lemald commented on assets/tests/contexts/notificationsContext.test.tsx
> -import { mount } from "enzyme"
Hooray for getting rid of old Enzyme tests!

2022-07-07 15:00 UTC, lemald requested changes
One relatively minor thing that can be changed, but overall looks good to me!

2022-07-08 14:54 UTC, lxhughes commented on test/skate_web/views/layout_view_test.exs
> -  end
good point! removed in b960e881

2022-07-08 18:39 UTC, lemald commented
Okay, this now looks good to me! I'm going to hold off on actually approving until we know we're ready to stop using FullStory, though.

2022-07-19 15:35 UTC, lemald approved these changes
👍

2022-07-19 15:38 UTC, merged