Add filter to remove private carrier routes
mbta/skate pull request #1642
Opened 2022-07-13 20:20 UTC by lxhughes

Asana: https://app.asana.com/0/1148853526253437/1201220680602259/f

Manually identifies the private carrier routes by route ID and filters them out of GTFS pull of routes.

2022-07-13 20:48 UTC, lemald requested changes
Basic logic looks good but I have a few comments.

2022-07-13 20:48 UTC, lemald commented on lib/schedule/gtfs/route.ex
> +  def bus_route_mbta?(row) do
Similarly, `bus_route_row?` is now only called internally, so it should probably also be private.

2022-07-14 18:26 UTC, lxhughes commented on lib/schedule/gtfs/route.ex
> +  def bus_route_validrow?(row) do
fixed in a440ae99

2022-07-14 18:26 UTC, lxhughes commented on lib/schedule/gtfs/route.ex
> +  def bus_route_mbta?(row) do
fixed in a440ae99

2022-07-14 18:58 UTC, lemald approved these changes

2022-07-15 14:11 UTC, merged