feat: Activate detour flow
mbta/skate pull request #2793
Opened 2024-09-12 18:19 UTC by joshlarson

Asana Ticket: https://app.asana.com/0/1205385723132845/1208153509160230/f

2024-09-18 14:49 UTC, hannahpurcell requested changes
Oh my, why are the commits all the same message haha!

Looking so good! One issue, though: select a duration, click Cancel, then try to activate again. The modal still shows the selected duration, but also doesn't allow the user to proceed to "next". I believe a cancel should erase the selected duration.

![Screenshot 2024-09-18 at 10 47 29 AM](https://github.com/user-attachments/assets/fdaf6bce-f32f-417d-8efd-ef85c727055e)

2024-09-18 14:55 UTC, hannahpurcell commented
Also, this is postponing hi-fi styling, right? Should I be leaving styling notes or save that for later?

2024-09-18 15:29 UTC, hannahpurcell commented on assets/tests/components/detours/diversionPage.activate.test.tsx
> +      // expect(activateButton.query()).not.toBeInTheDocument()
```suggestion
```

2024-09-18 15:32 UTC, hannahpurcell commented on assets/tests/components/detours/diversionPage.activate.test.tsx
> +      // expect(activateButton.query()).not.toBeInTheDocument()
Want this check to be back in place?

2024-09-23 15:40 UTC, joshlarson commented on assets/tests/components/detours/diversionPage.activate.test.tsx
> +      // expect(activateButton.query()).not.toBeInTheDocument()
Yep!

2024-09-23 15:41 UTC, joshlarson commented
@hannahpurcell I think I've fixed the bug you found (well, I fixed the bug that I was smashing my head into earlier - who knew that guard clauses could be so wonderful ✨ - hopefully this is the same one)

> Also, this is postponing hi-fi styling, right?

Yeah - hi-fi styling will come later, and TBH - it may come after we go live

2024-09-24 17:21 UTC, merged